---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 2019-06-06 15:21
---
print("hello world")

tab1 = { key1 = "val1", key2 = "val2", "val3" }
for i, v in pairs(tab1) do
    print(i .. "-" .. v)
end

local http = require("socket.http")
local response = http.request("http://www.baidu.com/")
print(response)

local isSuccess = type(X) == nil
print(isSuccess)

len = "tom"
print(#len)

a = {}
a["key"] = "11"
a[10] = 22
for k, v in pairs(a) do
    if k == 10 then
        break ;
    end
    print(k .. "-" .. v)

end

function factorial1(n)
    if n == 0 then
        return 1
    else
        return n * factorial1(n - 1)
    end
end

print(factorial1(5))
local srcStr = "aaaa%02d"
srcStr = string.gsub(srcStr, "a", "z", 3)
print(srcStr)
srcStr = string.format(srcStr, 3);
print(srcStr)
--[[
s = "Deadline is 30/05/1999, firm"
date = "%d%d/%d%d/%d%d%d%d"
index = string.find(s, date)
s = string.sub(s,index)
print(s)]]

s = "Deadline is 30/05/1999, firm"
date = "%d%d/%d%d/%d%d%d%d"
print(string.sub(s, string.find(s, date)))

-- Meta class
Shape = {area = 0}
-- 基础类方法 new
function Shape:new (o,side)
  o = o or {}
  setmetatable(o, self)
  self.__index = self
  side = side or 0
  self.area = side*side;
  return o
end
-- 基础类方法 printArea
function Shape:printArea ()
  print("面积为 ",self.area)
end

myshape = Shape:new(nil,10)

myshape:printArea()
