server:
  port: 1300
spring:
  application:
    name: user-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1100/eureka/
hystrix:
  metrics:
    polling-interval-ms: 2000
