spring:
  application:
    name: api-gateway
server:
  port: 5000
#zuul 配置
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId:
        user-service
    api-b:
      path: /api-b/**
      serviceId:
        feign-consumer
    api-c:
      path: /api-c/**
      url: forward:/local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1100/eureka/
ribbon:
  readTimeout: 60000
  connectTimeout: 60000
